"""Константы для интеграции ИКИ РАН: Космическая погода."""

DOMAIN = "xras_space_weather"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
URL_JSON_BASE = "https://xras.ru/txt"
URL_HTML_AURORA = "https://xras.ru/aurora.html"
URL_HTML_FLARES = "https://xras.ru/sun_flares.html"
UPDATE_INTERVAL_MINUTES = 30

# Полный список 104 городов из ha_generator_full_v4.html
CITIES = {
    "abakan": {"id": "QYPM", "name": "Абакан"},
    "anadyr": {"id": "SSWT", "name": "Анадырь"},
    "arkhangelsk": {"id": "SRLE", "name": "Архангельск"},
    "astrakhan": {"id": "PQM0", "name": "Астрахань"},
    "barnaul": {"id": "QWOZ", "name": "Барнаул"},
    "belgorod": {"id": "QGL2", "name": "Белгород"},
    "birobidzhan": {"id": "Q5T3", "name": "Биробиджан"},
    "blagoveshchensk": {"id": "QESN", "name": "Благовещенск"},
    "bratsk": {"id": "B9DU", "name": "Братск"},
    "bryansk": {"id": "QWKV", "name": "Брянск"},
    "vladivostok": {"id": "P7T0", "name": "Владивосток"},
    "vladikavkaz": {"id": "P6LQ", "name": "Владикавказ"},
    "vladimir": {"id": "RDLD", "name": "Владимир"},
    "volgograd": {"id": "Q4LP", "name": "Волгоград"},
    "vologda": {"id": "RVLC", "name": "Вологда"},
    "vorkuta": {"id": "VG5T", "name": "Воркута"},
    "voronezh": {"id": "QMLA", "name": "Воронеж"},
    "gorno-altaysk": {"id": "QOP6", "name": "Горно-Алтайск"},
    "grozny": {"id": "P8LT", "name": "Грозный"},
    "yekaterinburg": {"id": "RHN2", "name": "Екатеринбург"},
    "ivanovo": {"id": "RILF", "name": "Иваново"},
    "izhevsk": {"id": "RHMG", "name": "Ижевск"},
    "irkutsk": {"id": "QQQP", "name": "Иркутск"},
    "yoshkar-ola": {"id": "RGM0", "name": "Йошкар-Ола"},
    "kazan": {"id": "RBM3", "name": "Казань"},
    "kaliningrad": {"id": "R4JQ", "name": "Калининград"},
    "kaluga": {"id": "R3L1", "name": "Калуга"},
    "kemerovo": {"id": "R8P6", "name": "Кемерово"},
    "kirov": {"id": "RSM5", "name": "Киров"},
    "chisinau": {"id": "PUKF", "name": "Кишинёв"},
    "komsomolsk_on_amur": {"id": "KT8D", "name": "Комсомольск-на-Амуре"},
    "kostroma": {"id": "RNLF", "name": "Кострома"},
    "krasnodar": {"id": "PIL9", "name": "Краснодар"},
    "krasnoyarsk": {"id": "RCPR", "name": "Красноярск"},
    "kurgan": {"id": "R9NG", "name": "Курган"},
    "kursk": {"id": "QML1", "name": "Курск"},
    "kyzyl": {"id": "QMPV", "name": "Кызыл"},
    "lensk": {"id": "L9JF", "name": "Ленск"},
    "lipetsk": {"id": "QSLB", "name": "Липецк"},
    "magadan": {"id": "RXUK", "name": "Магадан"},
    "maikop": {"id": "PGLC", "name": "Майкоп"},
    "makhachkala": {"id": "P6LY", "name": "Махачкала"},
    "meshchovsk": {"id": "BEST", "name": "Мещовск"},
    "mineralnye_vody": {"id": "PDLL", "name": "Минеральные Воды"},
    "mirny_saha": {"id": "MH8W", "name": "Мирный (Якутия)"},
    "moscow": {"id": "RAL5", "name": "Москва"},
    "murmansk": {"id": "TIKR", "name": "Мурманск"},
    "naberezhnye_chelny": {"id": "RAMD", "name": "Набережные Челны"},
    "nazran": {"id": "P7LQ", "name": "Назрань"},
    "nalchik": {"id": "P9LN", "name": "Нальчик"},
    "naryan_mar": {"id": "NM03", "name": "Нарьян-Мар"},
    "neryungri": {"id": "NA8H", "name": "Нерюнгри"},
    "nizhnevartovsk": {"id": "NE9H", "name": "Нижневартовск"},
    "nizhny_novgorod": {"id": "RELO", "name": "Нижний Новгород"},
    "novgorod": {"id": "RRKM", "name": "Новгород"},
    "novokuznetsk": {"id": "NG7S", "name": "Новокузнецк"},
    "novosibirsk": {"id": "R6OX", "name": "Новосибирск"},
    "novy_urengoy": {"id": "NG4L", "name": "Новый Уренгой"},
    "norilsk": {"id": "NJ7D", "name": "Норильск"},
    "omsk": {"id": "R6O4", "name": "Омск"},
    "orenburg": {"id": "QNML", "name": "Оренбург"},
    "oryol": {"id": "QUL0", "name": "Орёл"},
    "penza": {"id": "QVLR", "name": "Пенза"},
    "perm": {"id": "ROMP", "name": "Пермь"},
    "petrozavodsk": {"id": "SBKV", "name": "Петрозаводск"},
    "petropavlovsk-kamchatsky": {"id": "QUV8", "name": "Петропавловск-Камчатский"},
    "pskov": {"id": "RNKD", "name": "Псков"},
    "rostov_on_don": {"id": "PVLB", "name": "Ростов-на-Дону"},
    "ryazan": {"id": "R4LB", "name": "Рязань"},
    "salekhard": {"id": "T3NK", "name": "Салехард"},
    "samara": {"id": "QVM6", "name": "Самара"},
    "saint_petersburg": {"id": "S0KJ", "name": "Санкт-Петербург"},
    "saransk": {"id": "R1LS", "name": "Саранск"},
    "saratov": {"id": "QLLU", "name": "Саратов"},
    "sevastopol": {"id": "S8FW", "name": "Севастополь"},
    "simferopol": {"id": "PIKU", "name": "Симферополь"},
    "smolensk": {"id": "R5KO", "name": "Смоленск"},
    "sochi": {"id": "PALB", "name": "Сочи"},
    "stavropol": {"id": "PILI", "name": "Ставрополь"},
    "station_vostok": {"id": "53QX", "name": "Станция Восток"},
    "station_mirny": {"id": "73PR", "name": "Станция Мирный"},
    "surgut": {"id": "SJ2L", "name": "Сургут"},
    "syktyvkar": {"id": "SAM8", "name": "Сыктывкар"},
    "tambov": {"id": "QSLG", "name": "Тамбов"},
    "tver": {"id": "REL0", "name": "Тверь"},
    "tiksi": {"id": "TH8S", "name": "Тикси"},
    "tolyatti": {"id": "QXM4", "name": "Тольятти"},
    "tomsk": {"id": "RFP3", "name": "Томск"},
    "tula": {"id": "R1L5", "name": "Тула"},
    "tyumen": {"id": "RJNH", "name": "Тюмень"},
    "ulan-ude": {"id": "QNQZ", "name": "Улан-Удэ"},
    "ulyanovsk": {"id": "R2M1", "name": "Ульяновск"},
    "ufa": {"id": "R4MO", "name": "Уфа"},
    "khabarovsk": {"id": "Q3T9", "name": "Хабаровск"},
    "khanty-mansiysk": {"id": "S6NR", "name": "Ханты-Мансийск"},
    "cheboksary": {"id": "RDLY", "name": "Чебоксары"},
    "chelyabinsk": {"id": "R7N4", "name": "Челябинск"},
    "cherepovets": {"id": "RVL6", "name": "Череповец"},
    "cherkessk": {"id": "PDLI", "name": "Черкесск"},
    "chita": {"id": "QORH", "name": "Чита"},
    "elista": {"id": "PQLP", "name": "Элиста"},
    "yuzhno-sakhalinsk": {"id": "PUTW", "name": "Южно-Сахалинск"},
    "yakutsk": {"id": "SCST", "name": "Якутск"},
    "yaroslavl": {"id": "RMLC", "name": "Ярославль"},
}
